import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import {
  LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,
} from "recharts";
import { AppLayout, useViewMode } from "@/components/AppLayout";
import { Card, PageHeader, DemoTag, StatusBadge } from "@/components/ui-bits";
import { LOCATIONS, PANCHAYATS, STATUS_META, type DayForecast, type Panchayat } from "@/lib/demo-data";
import { fetchFiveDayForecast } from "@/lib/api";

export const Route = createFileRoute("/forecast")({
  head: () => ({
    meta: [
      { title: "Panchayat Forecast — Krishivani" },
      { name: "description", content: "Panchayat-level weather forecast with 5-day outlook, generated by AI downscaling of Block-level forecasts. Demo data." },
      { property: "og:title", content: "Panchayat Forecast — Krishivani" },
      { property: "og:description", content: "Localized Panchayat-level weather forecast and 5-day outlook (demo data)." },
    ],
  }),
  component: ForecastPage,
});

function Select({ label, value, onChange, options }: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  options: { value: string; label: string }[];
}) {
  return (
    <label className="block text-xs">
      <span className="mb-1 block font-medium text-muted-foreground">{label}</span>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm outline-none focus:ring-2 focus:ring-ring"
      >
        {options.map((o) => (
          <option key={o.value} value={o.value}>{o.label}</option>
        ))}
      </select>
    </label>
  );
}

function ForecastPage() {
  const [panchayatId, setPanchayatId] = useState(PANCHAYATS[0]!.id);
  const [date, setDate] = useState("2026-09-28");
  const [fiveDay, setFiveDay] = useState<DayForecast[]>([]);
  const { mode } = useViewMode();

  const panchayat: Panchayat = PANCHAYATS.find((p) => p.id === panchayatId) ?? PANCHAYATS[0]!;

  useEffect(() => {
    fetchFiveDayForecast(panchayatId).then(setFiveDay);
  }, [panchayatId]);

  return (
    <AppLayout>
      <PageHeader
        title="Panchayat Forecast"
        subtitle="Localized forecast derived from the Block-level forecast via AI downscaling."
        demo
      />

      {/* Filters */}
      <Card className="mb-4">
        <div className="grid grid-cols-2 gap-3 md:grid-cols-5">
          <Select label="State" value={LOCATIONS.state} onChange={() => {}} options={[{ value: LOCATIONS.state, label: LOCATIONS.state }]} />
          <Select label="District" value={LOCATIONS.district} onChange={() => {}} options={[{ value: LOCATIONS.district, label: LOCATIONS.district }]} />
          <Select label="Block" value={LOCATIONS.block} onChange={() => {}} options={[{ value: LOCATIONS.block, label: LOCATIONS.block }]} />
          <Select
            label="Panchayat"
            value={panchayatId}
            onChange={setPanchayatId}
            options={PANCHAYATS.map((p) => ({ value: p.id, label: p.name }))}
          />
          <label className="block text-xs">
            <span className="mb-1 block font-medium text-muted-foreground">Date</span>
            <input
              type="date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
              className="w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm outline-none focus:ring-2 focus:ring-ring"
            />
          </label>
        </div>
      </Card>

      {mode === "farmer" ? (
        <Card title={`${panchayat.name} — Simple View`} action={<StatusBadge status={panchayat.status} />}>
          <div className="grid gap-4 text-sm sm:grid-cols-2">
            <p>🌧 Rain: <strong>{panchayat.rainProbabilityPct >= 70 ? "High" : panchayat.rainProbabilityPct >= 40 ? "Moderate" : "Low"}</strong></p>
            <p>🌡 Temperature: <strong>{panchayat.temperatureC}°C</strong></p>
            <p>⚠ Weather Risk: <strong>{STATUS_META[panchayat.status].label}</strong></p>
            <p>🌱 Advisory: Monitor drainage and plan farm activities according to local conditions.</p>
          </div>
        </Card>
      ) : (
        <>
          {/* Weather summary */}
          <Card title={`Weather Summary — ${panchayat.name}`} action={<StatusBadge status={panchayat.status} />}>
            <dl className="grid grid-cols-2 gap-4 text-sm sm:grid-cols-5">
              <div><dt className="text-xs text-muted-foreground">Rainfall</dt><dd className="text-lg font-semibold">{panchayat.rainfallMm} mm</dd></div>
              <div><dt className="text-xs text-muted-foreground">Temperature</dt><dd className="text-lg font-semibold">{panchayat.temperatureC}°C</dd></div>
              <div><dt className="text-xs text-muted-foreground">Humidity</dt><dd className="text-lg font-semibold">{panchayat.humidityPct}%</dd></div>
              <div><dt className="text-xs text-muted-foreground">Wind</dt><dd className="text-lg font-semibold">{panchayat.windKmh} km/h</dd></div>
              <div><dt className="text-xs text-muted-foreground">Rain Probability</dt><dd className="text-lg font-semibold">{panchayat.rainProbabilityPct}%</dd></div>
            </dl>
          </Card>

          {/* 5-day forecast charts */}
          <div className="mt-4 grid gap-4 lg:grid-cols-2">
            <Card title="5-Day Rainfall & Rain Probability" action={<DemoTag />}>
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={fiveDay}>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                    <XAxis dataKey="day" fontSize={12} />
                    <YAxis yAxisId="left" fontSize={12} unit=" mm" />
                    <YAxis yAxisId="right" orientation="right" fontSize={12} unit="%" />
                    <Tooltip />
                    <Legend />
                    <Bar yAxisId="left" dataKey="rainfallMm" name="Rainfall (mm)" fill="var(--sky)" radius={[2, 2, 0, 0]} />
                    <Line yAxisId="right" type="monotone" dataKey="rainProbabilityPct" name="Rain Prob. (%)" stroke="var(--primary)" strokeWidth={2} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </Card>
            <Card title="5-Day Temperature" action={<DemoTag />}>
              <div className="h-72">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={fiveDay}>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                    <XAxis dataKey="day" fontSize={12} />
                    <YAxis fontSize={12} unit="°C" domain={["dataMin - 2", "dataMax + 2"]} />
                    <Tooltip />
                    <Legend />
                    <Line type="monotone" dataKey="temperatureC" name="Temperature (°C)" stroke="var(--status-heavy)" strokeWidth={2} dot />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </Card>
          </div>
        </>
      )}
    </AppLayout>
  );
}
