/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as FarmerDashboardRouteImport } from './routes/farmer-dashboard'
import { Route as GovernmentDashboardRouteImport } from './routes/government-dashboard'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DownscalingRouteImport } from './routes/downscaling'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as PerformanceRouteImport } from './routes/performance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/farmer-dashboard',
  path: '/farmer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentDashboardRoute = GovernmentDashboardRouteImport.update({
  id: '/government-dashboard',
  path: '/government-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DownscalingRoute = DownscalingRouteImport.update({
  id: '/downscaling',
  path: '/downscaling',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/farmer-dashboard': typeof FarmerDashboardRoute
  '/government-dashboard': typeof GovernmentDashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/downscaling': typeof DownscalingRoute
  '/forecast': typeof ForecastRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/farmer-dashboard': typeof FarmerDashboardRoute
  '/government-dashboard': typeof GovernmentDashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/downscaling': typeof DownscalingRoute
  '/forecast': typeof ForecastRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/farmer-dashboard': typeof FarmerDashboardRoute
  '/government-dashboard': typeof GovernmentDashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/downscaling': typeof DownscalingRoute
  '/forecast': typeof ForecastRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory'
    | '/farmer-dashboard'
    | '/government-dashboard'
    | '/data-sources'
    | '/downscaling'
    | '/forecast'
    | '/login'
    | '/map'
    | '/performance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisory'
    | '/farmer-dashboard'
    | '/government-dashboard'
    | '/data-sources'
    | '/downscaling'
    | '/forecast'
    | '/login'
    | '/map'
    | '/performance'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory'
    | '/farmer-dashboard'
    | '/government-dashboard'
    | '/data-sources'
    | '/downscaling'
    | '/forecast'
    | '/login'
    | '/map'
    | '/performance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryRoute: typeof AdvisoryRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  GovernmentDashboardRoute: typeof GovernmentDashboardRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DownscalingRoute: typeof DownscalingRoute
  ForecastRoute: typeof ForecastRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PerformanceRoute: typeof PerformanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer-dashboard': {
      id: '/farmer-dashboard'
      path: '/farmer-dashboard'
      fullPath: '/farmer-dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-dashboard': {
      id: '/government-dashboard'
      path: '/government-dashboard'
      fullPath: '/government-dashboard'
      preLoaderRoute: typeof GovernmentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downscaling': {
      id: '/downscaling'
      path: '/downscaling'
      fullPath: '/downscaling'
      preLoaderRoute: typeof DownscalingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryRoute: AdvisoryRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  GovernmentDashboardRoute: GovernmentDashboardRoute,
  DataSourcesRoute: DataSourcesRoute,
  DownscalingRoute: DownscalingRoute,
  ForecastRoute: ForecastRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PerformanceRoute: PerformanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
